apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greet-access
rules:
  - apiGroups: ["demo.crd"]
    resources: ["greetings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]