apiVersion: apps.example.com/v1
kind: WebApp
metadata:
  labels:
    app.kubernetes.io/name: crd
    app.kubernetes.io/managed-by: kustomize
  name: webapp-sample
spec:
   image: nginx:1.27
   replicas: 2
   greeting: "hello"
